### ISSUE TITLE
Ask M-Lab to whitelist a Google Developer account

### ISSUE THREAD

**Issue by johnzimm** [hackoregon/broadbandmap-piecewise#17]
From: https://github.com/opentechinstitute/piecewise/blob/master/CONFIG.md

Piecewise requires a Google Account to be configured for ingesting M-Lab data from BigQuery. We recommend creating a separate account to use specifically for this purpose, rather than a personal account.

Create/Identify a Google account to use for your instance of Piecewise.

Email support@measurementlab.net to request that your Google account be whitelisted to query the M-Lab dataset.

Once M-Lab confirms your account is whitelisted, proceed.

**Comment by phxpdx** [comment]
Created Google account for this project, whitelisted it, and emailed account details to team. Will consider somewhere better to store and share account info.
