### ISSUE TITLE
Setup a project in Google Developer Console

### ISSUE THREAD

**Issue by johnzimm** [hackoregon/broadbandmap-piecewise#18]
From: https://github.com/opentechinstitute/piecewise/blob/master/CONFIG.md
1. Go to Google Developers console and log in using the account that was whitelisted by M-Lab: https://console.developers.google.com/project
2. Create a Google-API project (or choose an already existing project) and turn on permissions for the BigQuery API
3. Create a new client ID for the project, selecting "Installed Application" for Application Type and “Other” for Installed Application Type
4. Save the client_secrets.json file to the piecewise/piecewise folder (it should replace the old client_secrets.json file already in there)
5. Turn on billing for the project in Google console (you will not be billed because your account is whitelisted, but Big Query requires API applications to have billing enabled)
6. In the Overview section of your new project, note the Project ID number

**Comment by phxpdx** [comment]
Created Google account for this project, whitelisted it, and emailed account details to team. Will consider somewhere better to store and share account info.
