### ISSUE TITLE
Configure Piecewise for your location

### ISSUE THREAD

**Issue by johnzimm** [hackoregon/broadbandmap-piecewise#19]
- Geographic coordinates forming a bounding box, for example: [-122.6733398438,47.3630134401,-121.9509887695,47.8076208172]
- Shapefile(s) containing the sub-geographic areas by which the consumed raw data will be aggregated
- Topojson or geojson file(s) containing the same sub-geographic areas for the map front-end.
- A time range for which data should be consumed from M-Lab in format: Jan 1 2014 00:00:00

From: https://github.com/opentechinstitute/piecewise/blob/master/CONFIG.md

**Comment by phxpdx** [comment]
Added coordinates to center.js and piecewise_config.json
Added shapefile of census blocks in appropriately named folder
Added topojson of census blocks
Will pick a timerange, June 1 2016?

**Comment by johnzimm** [comment]
confirmed this is in the current portland branch.
