### ISSUE TITLE
Create ISP List for Portland

### ISSUE THREAD

**Issue by johnzimm** [hackoregon/broadbandmap-piecewise#7]
Generate a list of ISPs for Portland.  Additionally identify how they might be updated in the repository.

**Comment by ramonpichardo** [comment]
Directory: "broadbandmap-piecewise/portland_example/"
File: "piecewise_config.json" 

Updated file to reflect the ISPs serving Portland*:

"at&t": ["at&t mobility llc", "at&t services", "at&t wireless", "wayport"],
"centurylink": ["qwest", "embarq", "centurylink", "centurytel"],
"comcast": ["comcast cable communications", "xfinity"],
"cricket wireless": ["cricket wireless"],
"dish network": ["dishnet"],
"easystreet online": ["easystreet online"],
"freewire broadband": ["freewire broadband"],
"hughesnet": ["hughesnet"],
"integra telecom": ["integra telecom"],
"level3": ["level 3 communications", "glbx"],
"ls networks": ["ls networks"],
"mammoth networks": ["mammoth networks"],
"megapath": ["megapath"],
"sawnet": ["sawnet"],
"silver star telecom": ["silver star telecom"],
"sprint": ["sprint"],
"stephouse networks": ["stephouse networks"],
"t-mobile": ["t-mobile usa"],
"verizon": ["cellco partnership, dba, verizon wireless"],
"wave": ["wave broadband", "broadstripe", "condointernet.net"],
"xo communciations": ["xo communications"]

*Source: http://broadbandnow.com/Oregon/Portland

**Comment by ramonpichardo** [comment]
Resolved.
